apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: your-registry/flask-backend:latest
        ports:
        - containerPort: 5000
